#ifndef GETWAY_PROTOCOLO_TESTE1_H_INCLUDED
#define GETWAY_PROTOCOLO_TESTE1_H_INCLUDED

/// DEFINIÇÃO DE VALORES DE GETWAY
#define GET_1
GET_1 *get1;
#define GET_2
GET_2 *get2;
#define GET_3
GET_3 *get3;
#define GET_4
GET_4 *get4;

/// DEFINIÇÃO DE EQUIPAMENTO PARA GETWAY
#define GETWAY_RADIO
GETWAY_RADIO *RET_GET_RAD;
#define GETWAY_ROTEADOR
GETWAY_ROTEADOR *RET_GET_ROT;
#define GETWAY_SWITCHES
GETWAY_SWITCHES *RET_GET_SWI;
#define GETWAY_PPPoE
GETWAY_PPPoE *RET_GET_PPP;
#define GETWAY_WIRELESS
GETWAY_WIRELESS *RET_GET_WIN;
#define GETWAY_SERVER
GETWAY_SERVER *RET_GET_SER;

/// DETERMINA QUAL EQUIPAMENTO ESTA LANÇANDO GETWAY
#ifdef GETWAY_RADIO    > 0
#define GET_RAD
GET_RAD *get_rad;
#endif // GETWAY_RADIO

#ifdef GETWAY_ROTEADOR > 0
#define GET_ROT
GET_ROT *get_rot;
#endif // GETWAY_ROTEADOR

#ifdef GETWAY_SWITCHES > 0
#define GET_SWI
GET_SWI *get_swi;
#endif // GETWAY_SWITCHES

#ifdef GETWAY_PPPoE    > 0
#define GET_PPP
GET_PPP *get_ppp;
#endif // GETWAY_PPPoE

#ifdef GETWAY_WIRELESS > 0
#define GET_WIR
GET_WIR *get_wir;
#endif // GETWAY_WIRELESS

#ifdef GETWAY_SERVER   > 0
#define GET_SER
GET_SER *get_ser;
#endif // GETWAY_SERVER

#define CHAMADAS_GETEWAY
CHAMADAS_GETEWAY *chamas_geteway;

/// RETORNO DA ESTRUTURA DE CHAMADA PARA LEITURA E COMPARAÇÃO DE LEAYALT
#define MAX_TAM_GET
MAX_TAM_GET *MAX_TAM_GET1;

/// RETORNO DA FUNÇÃO DE LEITURA DE IP PARA ESCRITA NA TELA
#define RET_GATEWAY_ADRESS
RET_GATEWAY_ADRESS *RET_GATEWAY_ADRESS1;

#define RECEBE_INF_GETEWAY_HOST_IP
RECEBE_INF_GETEWAY_HOST_IP *recebe_inf_getewat_host_ip;

#define REC_GET_UNI
//uniform_int REC_GET_UNI  = {0x01&&0x22&&0x03&&0x04};
uniform_real_distribution REC_GET_UNI;
//#define RECPITION_GETWAY_UNIFICA
//RECPITION_GETWAY_UNIFICA *REC_GET_UNI;
//#undef REC_GET_UNI(0x01,0x02,0x03,0x04)


#endif // GETWAY_PROTOCOLO_TESTE1_H_INCLUDED
