#ifndef IPSCANNER_H_INCLUDED
#define IPSCANNER_H_INCLUDED

/// SALVA IP NA MEMORIA PARA CONSULTA DA CLASSE NA FAIXA
#define IP_SCANN_A
IP_SCANN_A *IPSCANN_A;

/// SALVA IP NA MEMORIA PARA CONSULTA DA CLASSE NA FAIXA
#define IP_SCANN_B
IP_SCANN_B *IPSCANN_B;

/// SALVA IP NA MEMORIA PARA CONSULTA DA CLASSE NA FAIXA
#define IP_SCANN_C
IP_SCANN_C *IPSCANN_C;

/// SALVA IP NA MEMORIA PARA CONSULTA DA CLASSE NA FAIXA
#define IP_SCANN_D
IP_SCANN_D *IPSCANN_D;

/// SALVA IP NA MEMORIA PARA CONSULTA DA CLASSE NA FAIXA
#define IP_SCANN_E
IP_SCANN_E *IPSCANN_E;

/// SALVA IP NA MEMORIA PARA CONSULTA DA CLASSE NA FAIXA
#define IP_SCANN_F
IP_SCANN_F *IPSCANN_F;

/// SALVA IP NA MEMORIA PARA CONSULTA DA CLASSE NA FAIXA
#define IP_SCANN_G
IP_SCANN_G *IPSCANN_G;

/// SALVA IP NA MEMORIA PARA CONSULTA DA CLASSE NA FAIXA
#define IP_SCANN_H
IP_SCANN_H *IPSCANN_H;

/// SALVA IP NA MEMORIA PARA CONSULTA DA CLASSE NA FAIXA
#define IP_SCANN_I
IP_SCANN_I *IPSCANN_I;

/// SALVA IP NA MEMORIA PARA CONSULTA DA CLASSE NA FAIXA
#define IP_SCANN_J
IP_SCANN_J *IPSCANN_J;

#endif // IPSCANNER_H_INCLUDED

